In [28]:
import pandas as pd
import os
import requests
from dotenv import load_dotenv

load_dotenv()
API_KEY = os.getenv("API_KEY")
headers = {
    'X-CMC_PRO_API_KEY': API_KEY,
    'Accepts': 'application/json',
}

URL = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest"
response = requests.get(URL, headers = headers).json()

In [42]:
df = pd.json_normalize(response['data'])
df.head(5)

,id,name,symbol,slug,infinite_supply,circulating_supply,total_supply,max_supply,date_added,num_market_pairs,...,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.slug,platform.name,platform.symbol,platform.token_address
0,1,Bitcoin,BTC,bitcoin,False,2.002027e+07,2.002027e+07,2.100000e+07,2010-07-13T00:00:00.000Z,12615,...,1.556757e+12,59.9437,1.632940e+12,NaN,2026-04-24T20:58:00.000Z,NaN,NaN,NaN,NaN,NaN
1,1027,Ethereum,ETH,ethereum,True,1.206891e+08,1.206891e+08,NaN,2015-08-07T00:00:00.000Z,11845,...,2.808520e+11,10.8143,2.808520e+11,NaN,2026-04-24T20:58:00.000Z,NaN,NaN,NaN,NaN,NaN
2,825,Tether USDt,USDT,tether,True,1.896653e+11,1.922199e+11,NaN,2015-02-25T00:00:00.000Z,178955,...,1.897279e+11,7.3048,1.922833e+11,NaN,2026-04-24T20:59:00.000Z,1027.0,ethereum,Ethereum,ETH,0xdac17f958d2ee523a2206206994597c13d831ec7
3,52,XRP,XRP,xrp,False,6.156968e+10,9.998568e+10,1.000000e+11,2013-08-04T00:00:00.000Z,1828,...,8.875187e+10,3.4174,1.441487e+11,NaN,2026-04-24T20:58:00.000Z,NaN,NaN,NaN,NaN,NaN
4,1839,BNB,BNB,bnb,False,1.347864e+08,1.347864e+08,1.347864e+08,2017-07-25T00:00:00.000Z,3195,...,8.600720e+10,3.3117,8.600720e+10,NaN,2026-04-24T20:58:00.000Z,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.sort_values('minted_market_cap', ascending=False, inplace=True)
df = df[['name', 'symbol', 'minted_market_cap', 'quote.USD.price', 'quote.USD.percent_change_30d']]
df.rename(columns={'quote.USD.price': 'price', 'quote.USD.percent_change_30d': 'percent_change_30d'}, inplace=True)
df['price'] = df['price'].round(2)
df['percent_change_30d'] = df['percent_change_30d'].round(2)
df.head(5)

          name symbol  minted_market_cap     price  percent_change_30d
0      Bitcoin    BTC       1.556757e+12  77759.04                9.53
1     Ethereum    ETH       2.808520e+11   2327.07                7.43
2  Tether USDt   USDT       1.922833e+11      1.00                0.07
3          XRP    XRP       1.441280e+11      1.44                1.93
4          BNB    BNB       8.600720e+10    638.10               -1.29

In [44]:
df

                 name symbol  minted_market_cap     price  percent_change_30d
0             Bitcoin    BTC       1.556757e+12  77759.04                9.53
1            Ethereum    ETH       2.808520e+11   2327.07                7.43
2         Tether USDt   USDT       1.922833e+11      1.00                0.07
3                 XRP    XRP       1.441280e+11      1.44                1.93
4                 BNB    BNB       8.600720e+10    638.10               -1.29
..                ...    ...                ...       ...                 ...
90             Stacks    STX       4.174652e+08      0.23               -4.59
91  First Digital USD  FDUSD       4.150272e+08      1.00               -0.05
92              Tezos    XTZ       4.122596e+08      0.37               -3.67
98          Sun [New]    SUN       3.724176e+08      0.02                2.89
99            SPX6900    SPX       3.591958e+08      0.39               28.70

[100 rows x 5 columns]

In [45]:
symbol = input("Enter the symbol of the cryptocurrency you want to search for: ").upper()
if symbol in df['symbol'].values:
    crypto = df[df['symbol'] == symbol]
    print(crypto)

       name symbol  minted_market_cap    price  percent_change_30d
1  Ethereum    ETH       2.808520e+11  2327.07                7.43